services:
  - type: web
    name: mti-registration-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mti-postgres-db
          property: connectionString

databases:
  - name: mti-postgres-db
    databaseName: mti_registration_db
    user: mti_admin
    plan: free
